// astro.config.mjs
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import svelte from '@astrojs/svelte';

export default defineConfig({
	site: 'https://kb.elementary-interactive.dev',
	integrations: [
		starlight({
			title: 'Nitrogen',
			description: 'Frontend Ecosystem for the Nitrogen platform',
			social: [
				{
					icon: 'gitlab',
					label: 'GitLab',
					href: 'https://git.elementary-interactive.dev/elementary-interactive/nitrogen/nitrogen-docs'
				}
			],
			// Starlight 0.39 removed the `{ label, autogenerate }` short form.
			// Every group now needs an explicit `items` array; autogenerated
			// directories live inside that array as `{ autogenerate: { ... } }`.
			sidebar: [
				{
					label: 'Getting Started',
					items: [{ autogenerate: { directory: 'getting-started' } }]
				},
				{
					label: 'Packages',
					items: [
						{
							label: 'frontend-seo',
							items: [{ autogenerate: { directory: 'packages/frontend-seo' } }]
						},
						{
							label: 'frontend-tracking',
							items: [{ autogenerate: { directory: 'packages/frontend-tracking' } }]
						},
						{
							label: 'frontend-legal',
							items: [{ autogenerate: { directory: 'packages/frontend-legal' } }]
						}
					]
				},
				{
					label: 'SEO',
					items: [{ autogenerate: { directory: 'seo' } }]
				},
				{
					label: 'Skills & Cookbook',
					items: [{ autogenerate: { directory: 'skills' } }]
				},
				{
					label: 'ADR (Architecture Decisions)',
					items: [{ autogenerate: { directory: 'adr' } }]
				},
				{
					label: 'Reference',
					items: [{ autogenerate: { directory: 'reference' } }]
				}
			],
			customCss: ['./src/styles/custom.css'],
			head: [
				// Deliberately no tracking on the docs site itself — meta-irony
				// of slapping a consent banner on top of the docs that ship the
				// consent banner.
			],
			// `root` locale means English is served from `src/content/docs/`
			// without a `/en/` URL prefix. Naming the locale `en` (without
			// `root`) made Starlight look for content at `src/content/docs/en/`
			// and find nothing — the sidebar rendered every group with an
			// empty `<ul>`. When Hungarian is added in a follow-up ticket, it
			// goes in alongside this entry as `hu: { label: 'Magyar', lang: 'hu' }`
			// and its content lives at `src/content/docs/hu/`.
			defaultLocale: 'root',
			locales: {
				root: { label: 'English', lang: 'en' }
			}
		}),
		svelte() // enables Svelte component demos embedded in docs pages
	]
});
