name: Mirror to GitLab

on:
  push:
    branches: ["**"]
    tags: ["**"]
  delete: {}
  create: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.GITLAB_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Mirror to GitLab
        env:
          GITLAB_TARGET_URL: ssh://git@git.elementary-interactive.dev:5022/elementary-interactive/nitrogen/nitrogen-docs.git
        run: |
          git remote add gitlab "$GITLAB_TARGET_URL"
          git push gitlab --all --force
          git push gitlab --tags --force
